name: valet-travis-languages-testing/php-example
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
        tools: phpunit
    - run: phpunit
    strategy:
      matrix:
        php:
        - 7.0
